version: 0.2
phases:
  install:
    commands:
      - echo "install"
      - echo "java -version"
      - java --version
  pre_build:
    commands:
      - echo "pre_build"
  build:
    commands:
    - echo "build"
    - mvn package -D spring.profiles.active=dev
  post_build:
    commands:
    - echo "post_build"